service: petshop

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  environment:
    IS_SERVERLESS: true
    BUCKET: petbucketkksomething

package:
  exclude:
    - tests/**
    - .git/**
    - coverage/**
    - .sonar/**
    - src/**
    - node_modules/@types/**
    - testresults
    - build/**/*.js.map
    - build/test/**
    - sonar-project.properties
    - versioning.js
    - tsconfig.json


  
functions:
  pets:
    handler: build/src/functions/pets/handler.pets
    events:
      - http: 
          path: pets/heartbeat
          method: GET
      - http:
          path: pets
          method: GET
      - http:
          path: pets
          method: POST
  auth:
    handler: build/src/functions/auth/handler.auth
    events:
      - http:
          path: auth/heartbeat
          method: GET
      - http:
          path: auth
          method: POST
  mockglu:
    handler: build/src/functions/mockglu/handler.glu
    events:
      - http:
          path: glu/heartbeat
          method: GET
      - http:
          path: glu
          method: POST

plugins:
  - serverless-offline