service: petshop

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    IS_SERVERLESS: true

package:
  exclude:
    - tests/**
    - .git/**
    - coverage/**
    - .sonar/**
    - functions/**
    - node_modules/@types/**
    - testresults
    - build/tests/**
    - src/**
    - sonar-project.properties
    - versioning.js
    - tsconfig.json
    - build/**/*.js.map


  
functions:
  pets:
    handler: build/src/functions/pets/handler.pets
    events:
      - http:
          path: users/create
          method: get

plugins:
  - serverless-offline