service: petshop

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    IS_SERVERLESS: true

package:
  exclude:
    - tests/**
    - .git/**
    - coverage/**
    - .sonar/**
    - src/**
    - node_modules/@types/**
    - testresults
    - build/**/*.js.map
    - build/test/**
    - sonar-project.properties
    - versioning.js
    - tsconfig.json


  
functions:
  pets:
    handler: build/src/functions/pets/handler.pets
    events:
      - http:
          path: pets
          method: GET
      - http:
          path: pets
          method: POST

plugins:
  - serverless-offline