service: petshop

provider:
  name: aws
  runtime: nodejs4.3

package:
  exclude:
    - tests/**
    - .git/**
    - coverage/**
    - .sonar/**
    - functions/**
    - node_modules/@types/**
    - testresults

functions:
  pets:
    handler: build/functions/pets/handler.pets
    events:
      - http:
          path: users/create
          method: get

plugins:
  - serverless-offline